### PR TITLE
Update to 1.15 and some tweaks.

### PR DESCRIPTION
**Pull request by LambdAurora**
Just updated to 1.15 and replaced that damn requires to depends.

### CODE REVIEW

**Review by Yoghurt4C — CHANGES_REQUESTED** [review]
dont put emojis there ur bad

**Comment by LambdAurora** [comment]
What emojis?

**Comment by Yoghurt4C** [comment]
image
scung

**Comment by LambdAurora** [comment]
It was a bad dream!

**Comment by Draylar** [comment]
thank you first time contributor lambd aurora for your contritbution

**Pull request merged**
